[package]
edition = "2021"
authors = ["Drop-OSS"]
name = "droplet-rs"
version = "0.7.1"
license = "AGPL-3.0-only"
description = "Droplet is a `napi.rs` Rust/Node.js package full of high-performance and low-level utils for Drop"
[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
time-macros = "0.2.22"
time = "0.3.41"
webpki = "0.22.4"
ring = "0.17.14"

[dependencies.x509-parser]
version = "0.17.0"
features = ["verify"]

[dependencies.rcgen]
version = "0.13.2"
features = ["crypto", "pem", "x509-parser"]

[profile.release]
lto = true
strip = "symbols"
